### ISSUE TITLE
 Generic type 'NguCarousel<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by yogeshbansal** [sheikalthaf/ngu-carousel#106]
I have switch from ngx-carousel to @ngu-carousel. After installing it and following the steps mentioned in the guide. Now, I have getting this error. could you please let me know, what should i pass a type.

Error:  Generic type 'NguCarousel<T>' requires 1 type argument(s).

**Comment by sheikalthaf** [comment]
@yogeshbansal Now carousel supports the typing with the data. Just pass you data interface to the carousel. If you don't want any typings simply set any.

Thanks

**Comment by vg22** [comment]
Hi @sheikalthaf , if I pass <any>, I get the following error. Can you please help. Thanks.
[ts]
Type '{ grid: { xs: number; sm: number; md: number; lg: number; all: number; }; slide: number; speed: n...' is not assignable to type 'NguCarousel<any>'.
  Object literal may only specify known properties, and 'grid' does not exist in type 'NguCarousel<any>'.

**Comment by NambiRcggs** [comment]
I got the same issue this guys got some beta version testing,in 1.4.9.The one i was using is 1.4.8.
after npm insall it got upgraded to 1.5.5 they got some breaking changes thr.
Update your package json it might be pointing with ngu/carousel:^1.4.8 change that and to ngu/carousel:1.4.8 and reinstall

**Comment by Procisz** [comment]
Hello guys,
I have the same issue and I can't find any solution here, yet. :(
Generic type 'NguCarousel<T>' requires 1 type argument(s).

I tried to:
-Pass type "<any>". If I do this, the following error message appears (because of they key "point"):
     Type '{ visible: true; pointStyles: string; }' is not assignable to type 'boolean'.ts(2322)
     ngu-carousel.d.ts(29, 5): The expected type comes from property 'point' which is declared here on type 'NguCarousel<any>'
AND (because of they key "touch")
     Type 'boolean' is not assignable to type 'Touch'.ts(2322)
     ngu-carousel.d.ts(2, 5): The expected type comes from property 'touch' which is declared here on type 'NguCarousel<any>'
- Comment point and touch out, but the following error appears (because of they key "grid"):
     Type '{ grid: { xs: number; sm: number; md: number; lg: number; xl: number; all: number; }; slide: number; speed: number; 
      animation: string; load: number; easing: string; }' is not assignable to type 'NguCarousel<any>'.
       Object literal may only specify known properties, and 'grid' does not exist in type '
- Comment out of all the problematic key from this Object, but I finally got this error on carouselTile:
     Type '{ speed: number; load: number; easing: string; }' is missing the following properties from type 'NguCarousel<any>': _el, 
     _renderer, _differs, platformId, and 94 more.


This is my .ts file with the default options and template based on https://github.com/uiuniversal/ngu-carousel "Tile with custom point style":

import { NguCarousel } from '@ngu/carousel';

[...]

export class FeaturedComponent implements OnInit {
  public carouselTileItems: Array<any> = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
  public carouselTile: NguCarousel<any> = { // Problem is here
    grid: { xs: 2, sm: 3, md: 3, lg: 5, xl: 5, all: 0 },
    slide: 2,
    speed: 400,
    animation: 'lazy',
    point: {
      visible: true,
      pointStyles: `
          .ngucarouselPoint {
            list-style-type: none;
            text-align: center;
            padding: 12px;
            margin: 0;
            white-space: nowrap;
            overflow: auto;
            box-sizing: border-box;
          }
          .ngucarouselPoint li {
            display: inline-block;
            border-radius: 50%;
            border: 2px solid rgba(0, 0, 0, 0.55);
            padding: 4px;
            margin: 0 3px;
            transition-timing-function: cubic-bezier(.17, .67, .83, .67);
            transition: .4s;
          }
          .ngucarouselPoint li.active {
              background: #6b6b6b;
              transform: scale(1.2);
          }
        `
    },
    load: 2,
    touch: true,
    easing: 'ease'
  }

  constructor() { }

  ngOnInit() { }

  public carouselTileLoad(evt: any) {
    const len = this.carouselTileItems.length
    if (len <= 30) {
      for (let i = len; i < len + 10; i++) {
        this.carouselTileItems.push(i);
      }
    }
  }
}
