### ISSUE TITLE
Window undefined Hammerjs

### ISSUE THREAD

**Issue by MatthijsH85** [sheikalthaf/ngu-carousel#14]
When I run application, I get the following message:

})(window, document, 'Hammer');
ReferenceError: window is not defined

This version of the plugin was supposed to solve that problem for the serversided rendering, right?

**Comment by sheikalthaf** [comment]
This issue is already solved. Follow my guidelines in readme file

**Comment by vivekdoshi2** [comment]
I am getting another error : 

```
/Volumes/MAC-DATA/Angular/landonearth/node_modules/ion-rangeslider/js/ion.rangeSlider.js:19
        factory(require("jquery"), document, window, navigator);
                                   ^
ReferenceError: document is not defined
```

**Comment by polymer940c** [comment]
@sheikalthaf Where in you readme? No mention of window in your readme. can you be more specific?

**Comment by fridolin-koch** [comment]
I'm currently implementing SSR for our app, it turns out that mocking the window object leads to a bunch of issues with other libraries. The problem is that I then get:

```
ERROR ReferenceError: window is not defined
    at NguCarousel.ngAfterViewInit (webpack:///./node_modules/@ngu/carousel/fesm5/ngu-carousel.js?:417:9)
```
I fixed this issues by changing the window check: https://github.com/sheikalthaf/ngu-carousel/pull/96

I'm not sure if this has any side effects.
