### ISSUE TITLE
Anyone facing issue with angular universal using this carousel?

### ISSUE THREAD

**Issue by sheikalthaf** [sheikalthaf/ngu-carousel#2]

**Comment by AtanasChachev** [comment]
Hi , I've just experienced the following issue: 

![carousel_issue](https://user-images.githubusercontent.com/10319093/33671732-163fc3c6-dab1-11e7-990d-301ec4855f40.png)

**Comment by AtanasChachev** [comment]
@sheikalthaf do you know how this issue can be solved? Thanks.

**Comment by sheikalthaf** [comment]
@AtanasChachev Fixed the issue. Thanks for reporting. Will push the update

**Comment by AtanasChachev** [comment]
@sheikalthaf love u

**Comment by seanlon** [comment]
hello @sheikalthaf , same issue encountered. Pushed already the issue?

**Comment by sheikalthaf** [comment]
@AtanasChachev @seanlon no update not pushed. will push the update within few hours

**Comment by seanlon** [comment]
@sheikalthaf  still waiting..

**Comment by sheikalthaf** [comment]
@AtanasChachev @seanlon Update now live v1.4.2. Thanks for the support and love

**Comment by AtanasChachev** [comment]
@sheikalthaf everything is okay now , god bless ya bro.

**Comment by seanlon** [comment]
@sheikalthaf  llove you bro!!! 💋 👍  god bless you

@AtanasChachev thanks for raising this !!

**Comment by AtanasChachev** [comment]
@sheikalthaf One more issue but it's kinda rendering issue. When the carousel is initialized at first , everything is okay , but then when I start swiping/changing slides , the slider becomes kinda blurry ( the text and the image ) I've tried with translateZ(0) and other options  but don't work , I don't know if I`m the only one experiencing this. Since @seanlon is using your plugin as well , can you please tell if  you are experiencing that issue as well thanks!

**Comment by seanlon** [comment]
@sheikalthaf  @AtanasChachev  for me this issue closed. Thanks!
@AtanasChachev  i didnt face the blurry image issue. Would you please close this issue and open a new open issue?

**Comment by sheikalthaf** [comment]
@gimox I didn't faced any crash while resizing. Any other reason for crashing?. 
Thanks for using.
