### ISSUE TITLE
Can be Hammer a dependency of the package itself?

### ISSUE THREAD

**Issue by silversonicaxel** [sheikalthaf/ngu-carousel#38]
Is there a reason why I need to install _ngu-carousel_ and separately _hammerjs_ ?
If I need a carousel, I want to install the carousel only, not also hammerjs as a second library.

**Comment by sheikalthaf** [comment]
Hammerjs is a seperate library for touch. Why u need to install it as a seperate package because angular material uses the same library for there component. If i included in my package it not be availabe outside of my carousel. Need to install it again to use for other components. It will be duplicated so to avoid that we need to install it seperately

**Comment by silversonicaxel** [comment]
I understand your concerns, but if I want to install just ngu-carousel, this will never work in my project because I need also to install HammerJs. When, if HammerJs was already a dependency, it would be a standalone / indipendent package. But, thanks for clarification.
