### ISSUE TITLE
Regression 1.4.9-beta-3, build error

### ISSUE THREAD

**Issue by MatthiasKunnen** [sheikalthaf/ngu-carousel#73]
I can't build 1.4.9-beta-3 for production, `ng build --aot --prod`. It works using 1.4.9-beta-2.
Error:
```
ERROR in ./node_modules/@ngu/carousel/carousel.ngfactory.js
Module not found: Error: Can't resolve 'carousel' in '/opt/atlassian/pipelines/agent/build/node_modules/@ngu/carousel'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'carousel' in '/opt/atlassian/pipelines/agent/build/src/app'
ERROR in ./src/app/object.component.ngfactory.js
Module not found: Error: Can't resolve 'carousel' in '/opt/atlassian/pipelines/agent/build/src/app/object'
```

Side note: 1.4.9-beta-3 is not pushed to GitHub, only published to npm. The commits and tags are missing.

**Comment by sheikalthaf** [comment]
@MatthiasKunnen Hi,

I'm also tracking this issue. Don't know how to solve it. This issue is related to angular library package.

I need someone help to solve this issue.
I have updated the this repo with this issue.
Please clone it. And run these cmd:

`npm i`
`ng build --prod --project carousel`
`ng serve --aot`

Then you will hit the error

Thanks

**Comment by sheikalthaf** [comment]
@MatthiasKunnen This issue is fixed by upgrading to latest version carousel and angular. Thanks
